services:
  database:
    image: ${DOCKER_HUB_USERNAME:-ruthrogoway}/gallery_docker_project_db:latest
    container_name: gallery-db
    volumes:
      - db_data:/data
    networks:
      - gallery-network
    restart: unless-stopped

  backend:
    image: ${DOCKER_HUB_USERNAME:-ruthrogoway}/gallery_docker_project:latest
    container_name: backend
    environment:
      - DATABASE_URL=sqlite:/data/mydb.db
      - PORT=3007
      - HF_API_KEY=${HF_API_KEY}
    volumes:
      - db_data:/data
      - ai_images:/app/ai_images
    depends_on:
      - database
    networks:
      - gallery-network
    restart: unless-stopped

  backend-2:
    image: ${DOCKER_HUB_USERNAME:-ruthrogoway}/gallery_docker_project:latest
    container_name: backend-2
    environment:
      - DATABASE_URL=sqlite:/data/mydb.db
      - PORT=3008
      - HF_API_KEY=${HF_API_KEY}
    volumes:
      - db_data:/data
      - ai_images:/app/ai_images
    depends_on:
      - database
    networks:
      - gallery-network
    restart: unless-stopped

  nginx:
    image: ${DOCKER_HUB_USERNAME:-ruthrogoway}/gallery_docker_project_nginx:latest
    container_name: gallery-nginx
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - backend-2
    networks:
      - gallery-network
    volumes:
      - ai_images:/usr/share/nginx/html/generated-images
    restart: unless-stopped

  frontend:
    image: ${DOCKER_HUB_USERNAME:-ruthrogoway}/gallery_docker_project_frontend:latest
    container_name: gallery-frontend
    ports:
      - "3000:80"
    depends_on:
      - nginx
    networks:
      - gallery-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  ai_images:
    driver: local

networks:
  gallery-network:
    driver: bridge
